### Letian Xu
### 03-12-2019
### I have not given or received any unauthorized assistance on this assignment.

In [22]:
import numpy as np

## 2

In [23]:
a = np.arange(0,100,1)

## 3

In [24]:
b = np.arange(0,100,10)

## 4

In [25]:
c = np.linspace(0,10,101)

## 5

In [26]:
from random import randint


n = 10
d = []
for i in range(n):
    d_1 = []
    for i in range(n):
        d_1.append(randint(0, 9))
    d.append(b)

## 6

In [27]:
a = np.reshape(a, (10, 10))

## 7

In [28]:
a[4,5]

45

Sixth element on fifth row of numpy array

## 8

In [29]:
a[4]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

Fifth row of numpy array

## 9

In [30]:
np.sum(d)

4500

## 10

In [32]:
np.amax(a)

99

## 11

In [33]:
np.transpose(b)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## 12

In [34]:
np.add(a, d)

array([[  0,  11,  22,  33,  44,  55,  66,  77,  88,  99],
       [ 10,  21,  32,  43,  54,  65,  76,  87,  98, 109],
       [ 20,  31,  42,  53,  64,  75,  86,  97, 108, 119],
       [ 30,  41,  52,  63,  74,  85,  96, 107, 118, 129],
       [ 40,  51,  62,  73,  84,  95, 106, 117, 128, 139],
       [ 50,  61,  72,  83,  94, 105, 116, 127, 138, 149],
       [ 60,  71,  82,  93, 104, 115, 126, 137, 148, 159],
       [ 70,  81,  92, 103, 114, 125, 136, 147, 158, 169],
       [ 80,  91, 102, 113, 124, 135, 146, 157, 168, 179],
       [ 90, 101, 112, 123, 134, 145, 156, 167, 178, 189]])

## 13

In [35]:
np.multiply(a, d)

array([[   0,   10,   40,   90,  160,  250,  360,  490,  640,  810],
       [   0,  110,  240,  390,  560,  750,  960, 1190, 1440, 1710],
       [   0,  210,  440,  690,  960, 1250, 1560, 1890, 2240, 2610],
       [   0,  310,  640,  990, 1360, 1750, 2160, 2590, 3040, 3510],
       [   0,  410,  840, 1290, 1760, 2250, 2760, 3290, 3840, 4410],
       [   0,  510, 1040, 1590, 2160, 2750, 3360, 3990, 4640, 5310],
       [   0,  610, 1240, 1890, 2560, 3250, 3960, 4690, 5440, 6210],
       [   0,  710, 1440, 2190, 2960, 3750, 4560, 5390, 6240, 7110],
       [   0,  810, 1640, 2490, 3360, 4250, 5160, 6090, 7040, 8010],
       [   0,  910, 1840, 2790, 3760, 4750, 5760, 6790, 7840, 8910]])

## 14

In [36]:
np.dot(a, d)

array([[    0,   450,   900,  1350,  1800,  2250,  2700,  3150,  3600,
         4050],
       [    0,  1450,  2900,  4350,  5800,  7250,  8700, 10150, 11600,
        13050],
       [    0,  2450,  4900,  7350,  9800, 12250, 14700, 17150, 19600,
        22050],
       [    0,  3450,  6900, 10350, 13800, 17250, 20700, 24150, 27600,
        31050],
       [    0,  4450,  8900, 13350, 17800, 22250, 26700, 31150, 35600,
        40050],
       [    0,  5450, 10900, 16350, 21800, 27250, 32700, 38150, 43600,
        49050],
       [    0,  6450, 12900, 19350, 25800, 32250, 38700, 45150, 51600,
        58050],
       [    0,  7450, 14900, 22350, 29800, 37250, 44700, 52150, 59600,
        67050],
       [    0,  8450, 16900, 25350, 33800, 42250, 50700, 59150, 67600,
        76050],
       [    0,  9450, 18900, 28350, 37800, 47250, 56700, 66150, 75600,
        85050]])